# Generated by Django 3.1.7 on 2021-04-25 10:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('social', 'Social'), ('anti-drug', 'Anti Drug'), ('domestic-voilence', 'Domestic Voilence'), ('racial-discrimination', 'Racial Discrimination'), ('bullying', 'Bullying'), ('anti-beggary', 'Anti Beggary'), ('anti-rape', 'Anti Rape'), ('anti-abortion', 'Anti Abortion'), ('anti-gambling', 'Anti Gambling'), ('climate-change', 'Climate Change')], default='social', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('excerpt', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
