# Generated by Django 3.1.7 on 2021-04-25 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignpost',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='campaignpost',
            name='event_location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
