# Generated by Django 3.1.7 on 2021-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_remove_advertisementpost_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementpost',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='advertisementpost',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
